### ISSUE TITLE
Conversion PDF to AFP

### ISSUE THREAD

**Issue by wedisley** [yan74/afplib#1]
Hello!

I would like to use afplib to convert file PDF to AFP. I looked for all samples but I didn't found any case for it. Do you have an example to use this conversion?

Thank You so much.

**Comment by yan74** [comment]
Hi wedisley,

so afplib won't be able to "convert" PDF to AFP since it does not rasterize nor read the PDF. What it can do though is wrap the PDF into an object container and then you could create pages that reference pages in that object container. So basically for each PDF page you would have to create an empty AFP page using IOB to include the appropriate PDF page. As afplib is a low level library for reading and writing structured fields, you would have to know which fields to create and in which order. The MO:DCA specification will tell you what you would have to do but this is a lot of reading to do. Anyhow you would have to understand MO:DCA to make use of afplib. Having said that there is an example that "converts" (well not converts but includes) a PDF page into an AFP overlay at 

[afplib/org.afplib.samples/src/main/java/org/afplib/samples/PDF2Overlay.java](https://github.com/yan74/afplib/blob/master/org.afplib.samples/src/main/java/org/afplib/samples/PDF2Overlay.java)

Maybe that gets you starting.

**Comment by nitintomer** [comment]
Hi,

I am trying this code but getting an error when I try to open the resulting AFP in AFP Workbech Viewer.

The error is about missing resource and it says - Copy the missing resource into your resource path and reopen the file.

I tried to find it on my own, but couldn't. Please help.

Regards

Nitin

**Comment by yan74** [comment]
Hi @nitintomer,
please see #21 - I doubt AFP Workbench Viewer is able to display PDF object container. This software is ancient. You will need a newer AFP Viewer. You may try mine (www.afpworx.com)

**Comment by nitintomer** [comment]
Hi Yan,

I tried with this viewer as well, it shows nothing. In the status bar, it
says - opened filename.afp with 0 pages and 1 resource.

Regards
Nitin

**Comment by nitintomer** [comment]
Yes Yan, I read that. And it made sense.

I need to make sure that the AFP, thus generated is correct. And I don't
have have an AFP printer.

I am attaching the file, can you please check it?

Regards

Nitin

**Comment by yan74** [comment]
there was no file attached ... :)

**Comment by nitintomer** [comment]
Attaching again.
[0817bill.zip](https://github.com/yan74/afplib/files/2339042/0817bill.zip)

**Comment by yan74** [comment]
so this has - as expected - an overlay with a pdf object container in it. The overlay is correct. However it won't print as this is just an overlay. I modified org.afplib.samples.snippets.CreatePageWithPDFObject a bit so it uses your pdf to include on a page and also adjusted the page size to reflect your pdf size. The result is this:

[pdfoc-test.afp.zip](https://github.com/yan74/afplib/files/2339093/pdfoc-test.afp.zip)

Which you can print to an AFP printer which will produce something like this:

![side_20180831065908_00003](https://user-images.githubusercontent.com/7473685/44897702-e778f480-acfc-11e8-883b-5eb166339bd1.png)

So what you would need to do now is either

1) Split your pdf into 3 pdfs (one for each page) and create an AFP page for each of your PDF pages.

or

2) Create a resource group, include the pdf as object container and create AFP pages for each PDF page in the container having an IOB in each page pointing to the respective PDF page in the object container (using the ObjectOffset Triplet).

Hope that helps!

**Comment by nitintomer** [comment]
Thanks a lot Yan.

But when I am trying to open the file you sent in your viewer, I am getting the attached error message.

![yan](https://user-images.githubusercontent.com/7069385/44898850-b5c45580-ad1d-11e8-8c4d-3afd054cb8a6.png)

**Comment by yan74** [comment]
This is because the original sample code was how to place text on a page. This is still there - so in the png above you may notice that there is a "Hello World" above you pdf. The text needs a font and a codepage to display. This is why AFPWorX is telling you that you don't have those resources. An AFP printer normally has this font/codepage resident. So you can just ignore that error - or delete the fragment from the code that creates the text (BPT, PTX, EPT). In AFPWorX you can also delete this manually: 

https://youtu.be/4E6djzyjx4o
