### ISSUE TITLE
PDF TO AFP  ( Reading Byte Array)

### ISSUE THREAD

**Issue by mbefokam** [yan74/afplib#10]
Hi @yan74 , Thank you for this amazing library. I am trying to use it for my project. I read the MO:DCA documentation and now i am trying to convert a PDF to APF. I am using the issue #3 as my base code. But on of itself I have some problem. Here is my issue:

on this source code, you are passing a simple string "Hello World" on line

byte[] text = new String("Hello World").getBytes(Charset.forName("IBM500"));

I am trying to parse a pdf to byte array using two approaches they both don t work.
My PDF has text only.
1- the first approach is to I am using PdfReader.
PdfReader = reader = new PdfReader("mypdf");

byte[] text = reader.getPageContent(1);
but with this approach your library is not able to read my bytes and my get an ArraysOut of bound exception.

2 approach I read the PDF as an input stream.

InputStream pdffile = Buff....("mypdf")

then I used the pattern that you used in the case of pdf to overlay to right every bytes at the time.

byte[] buffer = new byte[MAX_SIZE]
int l
while ((l = pdffile.read(buffer)) >0)
PTX ptx = Afp.....
byte [] c = new byte[l]
System.arraycopy(buffer, o, c, 0, l)
aout.writeS(ptx)

This approach create a legit afp file but the file is empty.
Event when I used apache.commons.io.IOUtils to convert my input stream to byte arrays it still does not work.

The only side option that works a half way it to convert the pdf to string first then string to array bytes.
But in this case you lose the format and the string is written as a single line on the file.

Finally it will be helpful for people like my passionate about afp and following pretty closely your great work if you could have a pdf to afp clear example. The pdf should have like let say 2 pages, and should be a mixed of text, graph picture and bar code.

Thank you for your time.

**Comment by yan74** [comment]
Hi @mbefokam,

this may become a longer comment :) Before I answer to your issue above let me say the following: AFPlib is a low level API to create, read and modify structured fields. So it is most useful in analyzing existing AFP data and implementing fixes or small changes to that data. It could be the lower level of some higher API that is able to compose new AFP pages or convert from a different format like PDF. But this is a huge task to do and I would love to see an open source PDF to AFP converter based on AFPlib :)

So regarding PDF to AFP I can see three possible approaches:

1. convert the PDF to AFP (PDF text to PTOCA, Images to IOCA, PDF fonts to AFP fonts, Graphics to GOCA) - huge (!) task
2. render the PDF into images (using e.g. PDFBox) page by page and insert those images into AFP pages. #5 can help with the AFP part.
3. wrap the PDF into an object container and include that object container into pages. This works similar to #5 only that instead of including an image you include a full PDF and each reference to the object container also specifies on ObjectOffset (page from PDF to use)

If I find some time I will add an example on how to do 3. Now looking at your issue with not being able to read the PDF text and write that to PTOCA:

First you may want to ensure that the PDF text you read indeed is a text:

    PdfReader = reader = new PdfReader("mypdf");
    byte[] btext = reader.getPageContent(1);
    String pdftext = new String(btext, Charset.forName("UTF-8")); // whatever btext is encoded in UTF-8???
    System.out.println(pdftext); // see if that is ok
    byte[] text = pdftext.getBytes(Charset.forName("IBM500"));

Your second approach does not make any sense, since you cannot include a PDF into a PTX. Again for that I will provide a sample when I got time for it.

**Comment by mbefokam** [comment]
Hi @yan74 
Thank you for your explanation. This give me a clear picture of how to proceed.
I have a question about step 1.
1- convert the PDF to AFP (PDF text to PTOCA, Images to IOCA, PDF fonts to AFP fonts, Graphics to GOCA) - huge (!) task

Assuming that all these components( text, image and graph) are on the same pdf pages. I would like to know if when parsing the same pdf page from PDF text to PTOCA, PTOCA will grab only the text portion of the PDF and then when parsing the same pdf to IOCA, you library again will identify the email and grab those only.
The reason i am asking this question is to know if the coordinate of each component has to be set ahead or your library can self identify component on the format.
Thus if the coordinate have to be set ahead then it become hard to come out with a dynamic solution.

Thank you

**Comment by yan74** [comment]
Hi @mbefokam,

so afplib won't "recognize" pdf content. It would be your responsibility to convert a PDF element into AFP structured fields - whatever that means. AFPLib will help you write the structured fields, calculating length fields, providing the correct field IDs, ... The only exception is for some (!) image formats, like TIFF which can be embedded using an object container. But if for example your PDF contains a PNG (hope that actually is possible - I am no PDF expert) you would have to reformat to a supported format like TIFF or JPEG (although you better use JPEG if you want to print). Anyhow you would have to convert coordinates anyhow. Like I said this will be a huge (!) task to write a PDF to AFP converter - that's maybe why commercial converters are so expensive.

Regarding the code snippet that does not work - I guess I would need a full example (full class / project) to have a look at.

**Comment by mbefokam** [comment]
@yan74 I agree with that this is going to be urge task.
