### ISSUE TITLE
Question: Delete Text from PTX Structure

### ISSUE THREAD

**Issue by Pyre909** [yan74/afplib#18]
Hi @yan74 ,

I was wondering if the below scenarios are possible? I am currently looking through the library and looking to implement on how to do this.

Part 1
1. Search text based on TLE information.
2. Look in the PTX tag for the text that was grabbed from #1, then remove it. ( I am assuming that removing the text from this tag will make it so the text I want removed won't show when you use a viewer).

Part 2
1. Scan the AFP file look at the page and scan an area.(I need to dynamically check that this area has available white space to place other text on the page. If there is text already present then I don't want to overwrite/overprint).

Part 3
Also with your knowledge of AFP do you know if there is a way to programatically extract an image? I have tried searching, but no dice.....

If there is better solutions I am open to them. 

Thanks!

**Comment by yan74** [comment]
Hi @Pyre909,

1.1 you can certainly iterate through all structured fields and find TLE and their contents - see org.afplib.samples.DumpTLE

1.2 Similar to 1.1 just look for PTX and then iterate over the chained sequences. Now when you find a TRN you can try to extract the text as EBCDIC (should work 90% of the time):

    TRN trn = ...;
    String s = new String(trn.getTRNDATA(), Charset.forName("IBM500");
    s = ...; // remove from that String what you want to remove
    trn.setTRNData(s.getBytes(Charset.forName("IBM500")));
    // save the PTX

If the TRN is not encoded in EBCDIC (IBM500) and you happen to know the encoding replace the parametr in Charset.forName with that name. A more robust way is to look at the codepage that is used (mapped in a MCF), find the codepage in the resource group and see if there is a CGCSGID triplet that hopefully defines the Charset. Having said that - there are AFP composers creating codepages on the fly with no resemblance at all to standard codepages - then you're screwed or you have to OCR the font :)

2.1 This might be challenging as you will have to render the font in order to know the extent of a PTX. You may get away with calculating the offset of the text (starting point) using AMB and AMI and then make assumptions what space the text will occupy based on the number of chars in the TRN. But this is by no way fail-safe. If you really want to be sure you will have to write an AFP viewer :)

3. There is :) if it is an object container you just need to extract the data from the OCDs and there is your image. If it is an IOCA image that is a total different story. You will have to look at IOCA manual and based on the image encoding build the image from the ImageData (or BandedData - depends on how your image is build). It is certainly doable but is a lot of work.

**Comment by yan74** [comment]
@Pyre909 can I close this?
