### ISSUE TITLE
Not an Issue : GDD and GAD Object creation.

### ISSUE THREAD

**Issue by preddy321** [yan74/afplib#19]
Hi Ya, 

Is there a reference to create a sample AFP file with GDD and GAD Objects?

`out.writeStructuredField(new AfpBuilder()
				.create(GDD.class)); `

**Comment by yan74** [comment]
Hi @preddy321,

this actually is a weak spot of the library. I had it that GDD and GAD objects contain the GOCA commands - like any other structured field contains triplets (if they do). However problem turned out to be that GOCA commands can be spread across multiple GDD - even with one command partially being in the first and the remainder of the command in the second GDD. So my whole model of containment here does not work.

There needs to be some GOCAHelper that can construct commands based on a collection of GDDs... You are free to start coding this :) I would certainly help.

**Comment by preddy321** [comment]
Hi Yan, 

Sure,  am trying. Please guide me how to Start. 

Thanks.

**Comment by yan74** [comment]
@preddy321,

take a look at org.afplib.io.StructuredFieldFactory.triplet this is how afplib constructs triplets out of binary data. Now GOCA commands are not triplets, but pretty similar. They both have an identifier which defines the type (e.g. GLINE) and some also have a length specified. We need a similar function to the triplet one for commands. That function would loop through the binary data provided extracting identifier and length (if not implicitly defined by the type of command). Then for each GOCA command we would need some code block that constructs a Java object for that command. In org.afplib.generator.util/template/AfplibFactory.xpt is the code generating part for this:

			switch(id) {
			«FOREACH groupMembers AS t»
			«IF t.type.toString() == "GOCA"»
			case «t.id»: {
				«t.name» obj = AfplibFactory.eINSTANCE.create«t.name»();
				«FOREACH t.elements AS e»«IF e.metaType == Group»«EXPAND setter FOR e»«ENDIF»«ENDFOREACH»
				«FOREACH t.elements AS e»«IF e.metaType != Group»«EXPAND setter FOR e»«ENDIF»«ENDFOREACH»
				triplets.add(obj);
				break;
			}
			«ENDIF»
			«ENDFOREACH»
			}

I think these are the pieces needed for creating a GOCAHelper - just tie them together ;)

**Comment by preddy321** [comment]
working on it Yan, will update whats going on..............

**Comment by yan74** [comment]
@preddy321 for Issue #20 I needed to do similar for SDF - please see org.afplib.io.SDFHelper for your reference

**Comment by preddy321** [comment]
Hi Yan, 

Please check below, am trying to gey binary_sdf for WINDOW_SPECIFICATION Triplet for GDD. 

and creating GDD same as SDF Healper. but its not working. Please correct me if i did any mistake. 

`private static GDD createGDD(byte[] iddbuffer, int pos) {
		byte[] buf = new byte[pos];
		System.arraycopy(iddbuffer, 0, buf, 0, pos);
		GDD gdd = AfplibFactory.eINSTANCE.createGDD();
		gdd.setGOCAdes(buf);
		return gdd;
	}

	public static GDD[] sdf2GDD(List<Triplet> triplets) {

		List<GDD> gdds = new LinkedList<>();

		StructuredFieldFactory factory = new StructuredFieldFactory();
		byte[] gddbuffer = new byte[32000];
		byte[] buffer = new byte[32000];

		int pos = 0;
		for(Triplet t : triplets) {

			int length = factory.binary_sdf(buffer, 0, Arrays.asList(t));

			if(pos + length >= gddbuffer.length) {
				gdds.add(createGDD(gddbuffer, pos));
				pos = 0;
			}

			System.arraycopy(buffer, 0, gddbuffer, pos, length);
			pos += length;

		}
		gdds.add(createGDD(gddbuffer, pos));

		return (GDD[]) gdds.toArray(new GDD[gdds.size()]);
	}`


`int binary_sdf(byte[] buffer, int bstart, List<Triplet> triplets) {
		int start = bstart;

		for (Triplet m : triplets) {
			int length = 0;
			switch (m.eClass().getClassifierID()) {

			case AfplibPackage.DRAWING_ORDER_SUBSET :{
				m.setTripletId(222);
				DrawingOrderSubset obj = (DrawingOrderSubset) m;
				break;
			}
			case AfplibPackage.WINDOW_SPECIFICATION :
			 {
					m.setTripletId(223);
					WindowSpecification obj = (WindowSpecification) m;

					if ((223 & 0xff00) == 0xfe00) {
						if (length == 0)
							length = 4;
						byte[] bId = Data.toUnsignedShort(223);
						byte[] bLength = Data.toUnsignedShort(length - 4);
						buffer[start] = bId[0];
						buffer[start + 1] = bId[1];
						buffer[start + 2] = bLength[0];
						buffer[start + 3] = bLength[1];
					} else {
						if (length == 0)
							length = 2;
						buffer[start] = Data.toUnsignedByte(223)[0];
						buffer[start + 1] = Data.toUnsignedByte(length - 2)[0];
					}
					break;
				}`

**Comment by preddy321** [comment]
This is How creating Triplet.

`WindowSpecification windowSpecification =new AfpBuilder()
				.with(AfplibPackage.WINDOW_SPECIFICATION__FLAGS, 80)
				.with(AfplibPackage.WINDOW_SPECIFICATION__RES3, 0)
				.with(AfplibPackage.WINDOW_SPECIFICATION__CFORMAT, 0)
				.with(AfplibPackage.WINDOW_SPECIFICATION__UBASE, 1)
				.with(AfplibPackage.WINDOW_SPECIFICATION__XRESOL, 607)
				.with(AfplibPackage.WINDOW_SPECIFICATION__YRESOL, 1782)
				.with(AfplibPackage.WINDOW_SPECIFICATION__IMGXYRES, 7610)
				.with(AfplibPackage.WINDOW_SPECIFICATION__XLWIND, 607)
				.with(AfplibPackage.WINDOW_SPECIFICATION__XRWIND, 1782)
				.with(AfplibPackage.WINDOW_SPECIFICATION__YBWIND, -2913)
				.with(AfplibPackage.WINDOW_SPECIFICATION__YTWIND, -1148)
			.create(WindowSpecification.class);
		
			
		DrawingOrderSubset drawingOrderSubset = new AfpBuilder()
							.create(DrawingOrderSubset.class);
			
		List<Triplet> triplets = new LinkedList<>();
		triplets.addAll(Arrays.asList(windowSpecification, drawingOrderSubset));

		GDD[] gdds = SDFHelper.sdf2GDD(triplets);
		for(SF sf : gdds) {
			out.writeStructuredField(sf);
		}`

**Comment by harimurra** [comment]
Hi Yan, 

am Trying to Create GAD Object too. `case AfplibPackage.BEGIN_SEGMENT_COMMAND :{
				m.setTripletId(12);
				BeginSegmentCommand obj = (BeginSegmentCommand) m;
				
				if (obj.getSEGL() != null) {

					if (5 + 1 > length)
						length = 5 + 1;

				}

				if (obj.getNAME() != null) {

					Saver.saveUnsigned(buffer, start + 2, start + 5, obj.getNAME());

					if (5 + 1 > length)
						length = 5 + 1;

				}

				if (length == 0)
					length = 2;
				buffer[start] = Data.toUnsignedByte(12)[0];
				buffer[start + 1] = Data.toUnsignedByte(length - 2)[0];
				break;
			}`

**Comment by yan74** [comment]
well a GOCA command is not a SDF - SDF is a self defining field that is used in IOCA. GOCA commands are similar, but different - first off different GOCA command ids denote if there is a length field and how long (1 byte, 2 byte), whereas a SDF always has a length, but may have 1 or 2 byte id. So `binary_sdf` method is the wrong place. Also I would not code that by hand but rather have the code generator take care of creating command objects and storing these into binary arrays. So this is what I'd do:

1. Add a `binary_cmds` method in `AfplibFactory.xpt` which converts byte array into commands
2. Add a `cmds` method in `AfplibFactory.xpt` which converts commands into byte array

Both methods can be coded similar to `binary_sdf` and `sdf` - but the new ones need to be aware of the differences between sdf and goca (see GOCA specification).

    int binary_sdf(byte[] buffer, int bstart, List<Triplet> triplets);
    void sdf(List<Triplet> triplets, byte[] buffer, int start, int bufstop);

3. Create a new `GOCAHelper` similar to `SDFHelper` - now this should be easy since `GOCAHelper` will look almost the same as `SDFHelper` - with the difference that IPD will be a GAD and sdf of course cmd.

4. For GDD I think it is safe to actually implement the containment - so GDD contains a list of GOCA commands - once the `binary_cmd` and `cmds` methods are implemented from 1 and 2 this is as easy as changing the `model.xmi` and add references to the method in the `elementSetter FOR Group` and `groupSaver` :)

**Comment by yan74** [comment]
@preddy321, I gave a shot at 1. and 2. could you verify if the latest commit works for you creating the `GOCAHelper`?

**Comment by yan74** [comment]
@harimurra, the m.TripletId here denotes the GOCA command id (see GOCA manual) - basically the first byte of a GOCA command specifies which type that command is (e.g. GLINE).

**Comment by harimurra** [comment]
@yan74 ,

Thanks Yan, it's working.

**Comment by preddy321** [comment]
@yan74 

Thank you very much for sharing your knowledge. It is working.

Regards,
Reddy.
