### ISSUE TITLE
Not an Issue : How to create an IPD? 

### ISSUE THREAD

**Issue by vikasjadhav30** [yan74/afplib#20]
I am trying to create an AFP page in following format:
BAG:
      BIM:
             BOG:
                     OBD:
                     OBP:
                     MIO:
                     IDD:
             EOG
             IPD:
             IPD:
             IPD:
     EIM
EAG

Keep default property attributes.
please guide me to do so.

**Comment by yan74** [comment]
Hi @vikasjadhav30,

this was some effort - please see org.afplib.samples.snippets.CreatePageWithIOCAImage which creates a ioca-test.afp from an image called testdata/img_800x480_3x8bit_RGB_color_bars_CMYKWRGB.png. Since IOCA cannot render png I converted the image to CMYK and separated the color planes and stored the data uncompressed in .dat files - I used ImageMagick to do so since image manipulation in java is somewhat painful :)

The resulting AFP should look like this:

![ioca](https://user-images.githubusercontent.com/7473685/27036393-ff1c1756-4f84-11e7-87ee-0dc34076baf9.png)

**Comment by vikasjadhav30** [comment]
Thanks, Yan..

**Comment by gurunathrokkam** [comment]
Hi Yan,

Can you help on "**convert the image to CMYK and separated the color planes and stored the data uncompressed in .dat files**"?
