### ISSUE TITLE
PDF2Overlay output problem

### ISSUE THREAD

**Issue by abhijitingle** [yan74/afplib#21]
Hello,

I donwloaded source code for sample and setup on my local. I started with Junit - PDF2OverlayTest, it passed and generated the 01MUSRO file in tmp folder. 

Now my question is wheather it is afp file? why i am able to open that file in afp view (others generated from AfpCombineTest are able to do so)? and why file extension is not mentioned.

Please help me to resolve this issue PDF2Overlay. We have requirement to convert pdf to afp file.

**Comment by yan74** [comment]
Hi @abhijitingle,

like the name of the class implies this is an example on how to create an AFP overlay using an input PDF. Since afplib is a low level API and does not render nor understand PDF this is not converting the PDF to AFP but rather wrapping the PDF into an AFP object container. Modern printer will be able to render such constructs - most AFP viewers don't. Again this is just a sample on how to create such a construct with afplib. And since it is creating an overlay - which is similar to an AFP page, but different - you won't per se see anything in any viewer. You would have to include the overlay using an IPO into a page. There is a snippet in afplib that actually creates a page with some text on it. Although I wouldn't recommend afplib to create pages since again afplib is a low level api and you would have to do a lot of coding (as you can see in the CreatePage example). Another possibility is to include the BOC directly into a page (without creating and mapping an overlay). This would look like this:

![pdfinpage](https://user-images.githubusercontent.com/7473685/26981909-f0341522-4d36-11e7-93ae-133c7beded33.png)

I left out the extension .afp for the overlay since this is an external resource and usually print server look for the resource name (O1MUSRO) without any extension.

Hope that helps!
Yan

**Comment by yan74** [comment]
I added a CreatePageWithPDFObject snippet in org.afplib.samples.snippets for your convenience

**Comment by abhijitingle** [comment]
Thank you yan ...

**Comment by abhijitingle** [comment]
Hello yan, My pdf contain special characters, ibm500 do not include those charcter (i guess so). AFP file show garbage characters for the german characters like ä or Ü and ß

**Comment by yan74** [comment]
Hi @abhijitingle,

This should works anyhow as the PDF is embedded not converted. Maybe your AFP viewer does not work correctly? - Can you share the resulting AFP file?

**Comment by cristit** [comment]
Hi abhijitingle,

does your original pdf embed the fonts or at least the font subset(s)?

Best regards,
Cristian

**Comment by abhijitingle** [comment]
@yan74 , yes it worked with other pdf (with special characters). The reason is that the fonts used are customized font of my firm. 
I am using Adobe Reader to view the afp file, it shows the fonts in properties of afp file but do not display it correct.
@cristit , yes my pdf and afp file both shows the font subset in properties.

**Comment by yan74** [comment]
@abhijitingle I am sorry, but I don't understand :) How can you view an AFP with Acrobat Reader? Also if the customized fonts in your PDF are embedded as @cristit asked this would still be inside the PDF being contained in the AFP. So should work ... Again if you want I can have a look at the resulting AFP to see what is going wrong here - if you are able to share it.

**Comment by abhijitingle** [comment]
@yan74 its my bad, i could not explain the problem. I am not allowed to send the internal report or afp file. Can you suggest me the afp viewer which you  use to analyse. Thank u

**Comment by yan74** [comment]
You can try mine - www.afpworx.com
