### ISSUE TITLE
Not an Issue: How to create Font Resources?

### ISSUE THREAD

**Issue by FondAndy** [yan74/afplib#24]
I am creating AFP file with specific fonts. However it require font resources; could you please guide me how to create own font resources?  please check attched file for reference.
[FontResource.zip](https://github.com/yan74/afplib/files/1124733/FontResource.zip)

**Comment by yan74** [comment]
This is a raster font which can immediately be used by PTOCA text - use the CreatePage snippet from the samples directory to get started. In the code block that defines the font mapping you would want to map your font resource:


		MCF mcf = new AfpBuilder()											// Map coded font
				.withMember(new AfpBuilder()
						.withMember(new AfpBuilder()
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQN_TYPE, FullyQualifiedNameFQNType.CONST_CODE_PAGE_NAME_REFERENCE_VALUE)
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQN_FORMAT, FullyQualifiedNameFQNFormat.CONST_CHARACTERSTRING_VALUE)
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQ_NAME, "T1000395")  // codepage
								.create(FullyQualifiedName.class))			// Codepage reference
						.withMember(new AfpBuilder()
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQN_TYPE, FullyQualifiedNameFQNType.CONST_FONT_CHARACTER_SET_NAME_REFERENCE_VALUE)
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQN_FORMAT, FullyQualifiedNameFQNFormat.CONST_CHARACTERSTRING_VALUE)
								.with(AfplibPackage.FULLY_QUALIFIED_NAME__FQ_NAME, "C0EX00A0")  // Font
								.create(FullyQualifiedName.class))			// Font reference
						.withMember(new AfpBuilder()
								.with(AfplibPackage.RESOURCE_LOCAL_IDENTIFIER__RES_TYPE, ResourceLocalIdentifierResType.CONST_CODED_FONT_VALUE)
								.with(AfplibPackage.EXTENDED_RESOURCE_LOCAL_IDENTIFIER__RES_LID, 1) // identifier
								.create(ResourceLocalIdentifier.class))
						.create(MCFRG.class))
				.create(MCF.class);

 If you place your FontResource file as C0EX00A0 in your resource lib the resulting AFP created by CreatePage.java will use that font to display "Hello World". However I believe this font is being created by HP Extreme and is using a custom (generated) code page. You would need that code page as well and replace the code page mapped above (T1000395) with that.

Now I said place the font (and the code page) in the resource lib. Another way is to include those two files inline with the AFP file in the resource group. This would look like this:

    BRG
      BRS (RSName = C0EX00A0)
         (structured fields from your fontresource file)
      ERS
      BRS (RSName = <name of your code page)
         (structured fields from your code page file)
      ERS
    ERG
    BDT
       ....
    EDT

Hope that gives you a starting point.

**Comment by FondAndy** [comment]
Thank you for your answer.
What I actually wanted to know is how to create FontResource file like C0EX00A0? Is it predefined or any way to create our own FontResources(raster font )?

**Comment by yan74** [comment]
@FondAndy , sorry - reading with brain turned on sometimes helps ... You did say you want to create such a resource.

Well this is a bigger task then and it depends on which type of font you want to create - you sent a raster font as an example but just for completeness there are two other types: Outline Fonts (Type1) and TrueType. Creating a raster font or an outline font involve similar steps as they are considered to be FOCA fonts. There are some structured fields needed to describe the font and also map GCGID names to the glyphs (or characters) in the font. Then you would also need an appropriate code page that maps your code points in the TRNs to the GCGID names. Lastly for a raster font you would have to render each character (or glyph) into a 240dpi, 300dpi, ... black and white bitmap. This could be done with a library like freetype. For an outline font (type1) I guess you would need to have a type1 (.pfm) font as source - then you could just package the binary data into FNGs. However you'd still need to figure out the data positions of the glyphs in the font and to which actual character they belong (using the glyphname) and map that to a GCGID. - Wow lot of work. I believe there are font converters out there you could buy ... Now this is all possible using afplib and e.g. freetype but again some effort.

So the good part is that if you can use TrueType fonts (this depends on your output device) then this is much easier. You would only need to package the .ttf file into OCDs (see the PDF example in the snippets how to package binary data - here PDF - into OCDs) and put those into an object container (again see the sample on how to package PDF). With the difference that you won't need an environment group (BOG) and the object classification would look like this:

![obj](https://user-images.githubusercontent.com/7473685/27948307-b22ea804-62f9-11e7-8d27-cae87638c35f.png)

Just note that ttf font mapping in PTOCA is done using MDR instead of MCF. Also note that by default the code page is UTF-16 so you won't need a codepage.

I know this is all very high level but maybe this gives you a starting point for deciding which route you want to pursue.
