### ISSUE TITLE
AFPdump.java cannot find 5a magic byte 

### ISSUE THREAD

**Issue by mital1310** [yan74/afplib#33]
Hi Yan,

I am trying to process AFP Files (MODCA Annotations) to get annotations metadata. I think your AFPDump.java could help me achieve this but I am encountering  java.io.IOException: cannot find 5a magic byte. Can you please have a look at the sample file I have added!

[Text.afp.zip](https://github.com/yan74/afplib/files/1881981/Text.afp.zip)

 

Any help on this would be much appreciated.

**Comment by yan74** [comment]
Hi @mital1310,

your AFP seems to be valid although *very* unusual. Normally you'd have 0x5a in front of every structured field. I think very few AFP receivers would understand your AFP although again I came across some AFPs without 0x5a. afplib could be changed so that it does not insist on finding the 0x5a - you are welcome to try :)

**Comment by yan74** [comment]
see #22

**Comment by yan74** [comment]
Hi @mital1310,

can you double check your file does not work with afplib. Looks like I fixed this type of problem in https://github.com/yan74/afplib/commit/8079ffce57eeabd8a84aec24f886af07897e319b

**Comment by mital1310** [comment]
Thanks for getting back so quick @yan74 . I looked at the updated AfpInputStream.Java and I think that might help me.
